// <auto-generated />
namespace Projeto3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class Mercadinho3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mercadinho3));
        
        string IMigrationMetadata.Id
        {
            get { return "201911091348105_Mercadinho3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
