// <auto-generated />
namespace Projeto3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class TabeladeVendas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TabeladeVendas));
        
        string IMigrationMetadata.Id
        {
            get { return "201911111245203_Tabela de Vendas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
